#!/usr/bin/env python3
"""Install or refresh the pstack skill for pi.

Clones (or fast-forwards) the upstream pstack source, then writes one hidden,
opt-in wrapper skill and a Pi-adapted copy of the pstack tree. pi stops
recursing a skills directory at the first SKILL.md it finds, so the wrapper
registers one hidden skill while contributing zero system-prompt entries; every
file under skills/ stays readable by path.

Run: python3 ~/.pi/agent/skills/pstack-setup.py [repo_dir]

Re-running is safe. The wrapper is regenerated from this file, so put local
tweaks here rather than in the generated SKILL.md. A hand-edited SKILL.md is
backed up to SKILL.md.bak before it is replaced.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_URL = "https://github.com/cursor/plugins"
BRANCH = "main"
DEFAULT_REPO = Path.home() / "src" / "cursor-plugins"
SKILLS_DIR = Path(__file__).resolve().parent  # ~/.pi/agent/skills
TARGET = SKILLS_DIR / "pstack"  # the one registered skill
MARKER = "<!-- generated by pstack-setup.py -->"

WRAPPER = f"""---
name: pstack
description: Opt-in Pi adapter for pstack poteto workflows and leaf skills. Invoke with /skill:pstack followed by a task, or /skill:pstack followed by a leaf name and task.
disable-model-invocation: true
---

{MARKER}

# pstack

Use progressive discovery. Do not preload the skill tree.

## Routing

- `/skill:pstack <task>`: read `skills/poteto-mode/SKILL.md` in full, match the task to
  one playbook, then read only that playbook.
- `/skill:pstack <leaf> <task>`: when `<leaf>` exactly names a directory containing
  `skills/<leaf>/SKILL.md`, read that leaf in full and apply it directly. Use the router
  instead when the first word is not a leaf name.
- When a loaded file says to use, apply, invoke, run, or route through a named skill or
  `/<name>`, read `skills/<name>/SKILL.md` in full and follow it in the current turn.
  Nested leaves are not registered Pi skills. Do not try `/skill:<name>`.
- When a loaded file names a principle slug, read
  `skills/principle-<name>/SKILL.md` before applying or citing it.
- Load references and scripts only when the selected playbook or leaf requires them.

Resolve relative paths against the file that mentions them. In poteto-mode files,
resolve `playbooks/`, `references/`, and `scripts/` against `skills/poteto-mode/`.
Treat an upstream `pstack/skills/` prefix as `skills/` in this wrapper.

## Pi translation

- Users invoke this adapter with `/skill:pstack <task>`. `/poteto-mode` in upstream text
  means the already-loaded adapter. Pi does not register `/poteto-mode` as a command.
- `Task` means Pi's `subagent` tool. Omit unsupported Cursor fields such as
  `subagent_type`, `readonly`, `environment`, and `run_in_background`. Put read-only or
  write constraints in the delegated task. Calls are serialized even when upstream asks
  for parallel fan-out.
- For `subagent_type: "poteto-agent"`, begin the delegated task with `Read
  ~/.pi/agent/skills/pstack/SKILL.md in full and follow it.` Other routed leaves should
  pass their required prompt or reference content to the child as the leaf instructs.
- Let subagents inherit the active Pi model unless an available provider and model are
  explicitly chosen. Ignore Cursor model slugs, `~/.cursor/rules/pstack-models.mdc`, and
  `/setup-pstack`.
- `AskQuestion` means ask the user directly when no question tool is available.
- Not bundled, skip when referenced: `deslop`, `control-cli`, `control-ui`
  (cursor-team-kit), Cursor's built-in `/create-skill` and `/babysit`. `gh` covers PR work.

"""


def sync_repo(repo: Path) -> None:
    if not (repo / ".git").is_dir():
        repo.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", BRANCH, REPO_URL, str(repo)],
            check=True,
        )
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
        print(f"cloned {repo} at {commit}")
        return
    before = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
    fetch = subprocess.run(
        ["git", "fetch", "--depth", "1", "origin", BRANCH],
        cwd=repo,
        text=True,
        capture_output=True,
    )
    if fetch.returncode != 0:
        after = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
        print(f"update skipped, fetch failed ({before} -> {after}): {fetch.stderr.strip()}")
        return
    merge = subprocess.run(
        ["git", "merge", "--ff-only", "FETCH_HEAD"], cwd=repo, text=True, capture_output=True
    )
    after = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
    if merge.returncode != 0:
        print(f"update skipped, fast-forward merge failed ({before} -> {after}): {merge.stderr.strip()}")
        return
    print(f"updated {repo} {before} -> {after}")


def write_wrapper() -> None:
    TARGET.mkdir(parents=True, exist_ok=True)
    path = TARGET / "SKILL.md"
    if path.exists():
        old = path.read_text()
        if old == WRAPPER:
            return
        if MARKER not in old:
            shutil.copy(path, path.with_suffix(".md.bak"))
            print(f"backed up hand-edited {path.name} to {path.with_suffix('.md.bak').name}")
    path.write_text(WRAPPER)
    print(f"wrote {path}")


PI_REPLACEMENTS = (
    ("~/.cursor/projects/<slug>/agent-transcripts/<uuid>/<uuid>.jsonl", "the active workspace's agent-transcripts path named by the Pi system prompt"),
    ("~/.cursor/projects/*/", "other workspace transcript roots"),
    ("~/.cursor/rules/pstack-models.mdc", "an explicitly provided model configuration"),
    ("~/.cursor/skills/", "~/.pi/agent/skills/"),
    (".cursor/skills/", ".pi/skills/"),
    ("Cursor's built-in `create-skill`", "the `authoring-a-skill` playbook"),
    ("Cursor's built-in `/create-skill`", "the `authoring-a-skill` playbook"),
    ("Cursor's built-in create-skill", "the `authoring-a-skill` playbook"),
    ("Cursor's built-in babysit skill", "the built-in babysit skill"),
    ("Cursor environment", "Pi environment"),
    ("a Cursor restart", "a Pi restart"),
    ("Cursor restart", "Pi restart"),
    ("cursor location", "current editor location"),
    ("Cursor", "Pi"),
)


def adapt_skills(skills: Path) -> None:
    for path in skills.rglob("SKILL.md"):
        text = path.read_text()
        for old, new in PI_REPLACEMENTS:
            text = text.replace(old, new)
        path.write_text(text)

    poteto = skills / "poteto-mode" / "SKILL.md"
    if poteto.is_file():
        text = poteto.read_text()
        text = text.replace(
            "- Before commit → the `deslop` skill from the `cursor-team-kit` plugin (`/deslop`).",
            "- Before commit → run a locally available `deslop` skill. If it is not installed, skip it.",
        )
        text = text.replace(
            "- Shipping UI / IDE / CLI → the matching control skill. `cursor-team-kit` publishes `control-cli` (CLIs and TUIs) and `control-ui` (browser / Electron / web UIs). For bug fixes, reproduce first on the same surface yourself. Hand to the user only under the narrow Bug fix step 1 exception.",
            "- Shipping UI / IDE / CLI → use a matching locally available control skill when one exists. For bug fixes, reproduce first on the same surface yourself. Hand to the user only under the narrow Bug fix step 1 exception.",
        )
        text = text.replace(
            "**Defaults for every `Task` call.** `run_in_background: true`, agent mode (readonly strips MCP), file pointers not inlined context, explicit model per role (configurable via `/setup-pstack`. Defaults `grok-4.6-fast-xhigh` for code, `claude-fable-5-1-thinking-max` for prose and judgment). Code delegates tier by difficulty. The hardest changes (cross-cutting design, gnarly concurrency, subtle algorithms) go to your strongest judgment model (`claude-fable-5-1-thinking-max`), whether the task needs judgment on vague intent or is a precisely specified sequence of steps to execute to the letter. Trivial mechanical edits go to your fast code model. Per-role lines in the `/setup-pstack` rule override these defaults and the model choices in the routed skills (`how`, `why`, `arena`, `swarm`, `architect`, `interrogate`, `reflect`). A role with no line keeps its default, and a role line of `inherit-parent` or `auto` runs that role on the parent chat model (omit Task `model`).",
            "**Defaults for every `subagent` call.** Use file pointers instead of inlining large context. Let subagents inherit the active Pi model unless an explicitly available model is chosen. Put read-only or write constraints in the delegated task because this adapter does not support separate agent-mode flags. Calls may be serialized by the adapter even when a workflow requests fan-out.",
        )
        poteto.write_text(text)

    setup = skills / "setup-pstack" / "SKILL.md"
    if setup.is_file():
        setup.write_text(
            """---
name: setup-pstack
description: Explain Pi model selection for pstack workflows. Use when configuring pstack models is requested.
disable-model-invocation: true
---
# Setup pstack

Pi supplies the active model to `subagent` calls. This adapter does not use a
per-role model file or a separate setup command.

Let subagents inherit the active Pi model unless the caller explicitly chooses
an available provider and model. Put any read-only or write constraints in the
delegated task. Calls may be serialized by the adapter.
"""
        )

    bot_ui = skills / "make-bot-ui" / "SKILL.md"
    if bot_ui.is_file():
        bot_ui.write_text(
            """---
name: make-bot-ui
description: This workflow depends on a platform-specific automation service that is not bundled with Pi.
disable-model-invocation: true
---
# Make Bot UI

This workflow is not available in Pi. Skip it rather than guessing at an
equivalent webhook, credential store, or hosting integration.
"""
        )


def link_skills(repo: Path) -> None:
    src = repo / "pstack" / "skills"
    if not src.is_dir():
        sys.exit(f"no pstack skills at {src}, is the checkout broken?")
    link = TARGET / "skills"
    if link.is_symlink():
        link.unlink()
    elif link.exists():
        shutil.rmtree(link)
    shutil.copytree(src, link)
    adapt_skills(link)
    print(f"copied and adapted {src} -> {link}")


def check(repo: Path) -> None:
    wrapper = (TARGET / "SKILL.md").read_text()
    header, _, body = wrapper.partition("\n---\n")
    fields = dict(line.split(": ", 1) for line in header.removeprefix("---\n").splitlines())
    assert fields.get("name") == "pstack", "frontmatter missing or misordered"
    assert fields.get("disable-model-invocation") == "true", "pstack must be opt-in"
    # A bare ": " inside a value makes YAML read a nested mapping and pi drops the skill.
    assert all(": " not in v for v in fields.values()), f"colon in frontmatter value: {fields}"
    assert body.strip(), "wrapper body is empty"
    assert (TARGET / "skills").is_dir(), "missing adapted skills"
    for path in (TARGET / "skills").rglob("SKILL.md"):
        text = path.read_text()
        assert not re.search(r"\bcursor\b|\.cursor", text, re.IGNORECASE), f"unadapted platform reference: {path}"
    required = (
        TARGET / "skills" / "poteto-mode" / "SKILL.md",
        TARGET / "skills" / "poteto-mode" / "playbooks" / "feature.md",
    )
    for path in required:
        assert path.is_file(), f"missing required pstack file: {path}"
    count = len(list((TARGET / "skills").glob("*/SKILL.md")))
    print(f"ok: 1 hidden skill registered, 0 system-prompt entries; {count} pstack files readable under {TARGET}/skills")


def main() -> None:
    repo = Path(sys.argv[1]).expanduser() if len(sys.argv) > 1 else DEFAULT_REPO
    sync_repo(repo)
    write_wrapper()
    link_skills(repo)
    check(repo)


if __name__ == "__main__":
    main()
