#!/usr/bin/env python3
"""Install or refresh the pstack skill for pi.

Clones (or fast-forwards) cursor/plugins, then writes one hidden, opt-in wrapper
skill that exposes the whole pstack tree. pi stops recursing a skills directory
at the first SKILL.md it finds, so the wrapper registers one hidden skill while
contributing zero system-prompt entries; every file under skills/ stays
readable by path.

Run: python3 ~/.pi/agent/skills/pstack-setup.py [repo_dir]

Re-running is safe. The wrapper is regenerated from this file, so put local
tweaks here rather than in the generated SKILL.md. A hand-edited SKILL.md is
backed up to SKILL.md.bak before it is replaced.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

REPO_URL = "https://github.com/cursor/plugins"
BRANCH = "main"
DEFAULT_REPO = Path.home() / "src" / "cursor-plugins"
SKILLS_DIR = Path(__file__).resolve().parent  # ~/.pi/agent/skills
TARGET = SKILLS_DIR / "pstack"  # the one registered skill
MARKER = "<!-- generated by pstack-setup.py -->"

WRAPPER = f"""---
name: pstack
description: Opt-in Pi adapter for pstack poteto workflows and leaf skills. Invoke with /skill:pstack followed by a task, or /skill:pstack followed by a leaf name and task.
disable-model-invocation: true
---

{MARKER}

# pstack

Use progressive discovery. Do not preload the skill tree.

## Routing

- `/skill:pstack <task>`: read `skills/poteto-mode/SKILL.md` in full, match the task to
  one playbook, then read only that playbook.
- `/skill:pstack <leaf> <task>`: when `<leaf>` exactly names a directory containing
  `skills/<leaf>/SKILL.md`, read that leaf in full and apply it directly. Use the router
  instead when the first word is not a leaf name.
- When a loaded file says to use, apply, invoke, run, or route through a named skill or
  `/<name>`, read `skills/<name>/SKILL.md` in full and follow it in the current turn.
  Nested leaves are not registered Pi skills. Do not try `/skill:<name>`.
- When a loaded file names a principle slug, read
  `skills/principle-<name>/SKILL.md` before applying or citing it.
- Load references and scripts only when the selected playbook or leaf requires them.

Resolve relative paths against the file that mentions them. In poteto-mode files,
resolve `playbooks/`, `references/`, and `scripts/` against `skills/poteto-mode/`.
Treat an upstream `pstack/skills/` prefix as `skills/` in this wrapper.

## Pi translation

- Users invoke this adapter with `/skill:pstack <task>`. `/poteto-mode` in upstream text
  means the already-loaded adapter. Pi does not register `/poteto-mode` as a command.
- `Task` means Pi's `subagent` tool. Omit unsupported Cursor fields such as
  `subagent_type`, `readonly`, `environment`, and `run_in_background`. Put read-only or
  write constraints in the delegated task. Calls are serialized even when upstream asks
  for parallel fan-out.
- For `subagent_type: "poteto-agent"`, begin the delegated task with `Read
  ~/.pi/agent/skills/pstack/SKILL.md in full and follow it.` Other routed leaves should
  pass their required prompt or reference content to the child as the leaf instructs.
- Let subagents inherit the active Pi model unless an available provider and model are
  explicitly chosen. Ignore Cursor model slugs, `~/.cursor/rules/pstack-models.mdc`, and
  `/setup-pstack`.
- `AskQuestion` means ask the user directly when no question tool is available.
- Not bundled, skip when referenced: `deslop`, `control-cli`, `control-ui`
  (cursor-team-kit), Cursor's built-in `/create-skill` and `/babysit`. `gh` covers PR work.

"""


def sync_repo(repo: Path) -> None:
    if not (repo / ".git").is_dir():
        repo.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", BRANCH, REPO_URL, str(repo)],
            check=True,
        )
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
        print(f"cloned {repo} at {commit}")
        return
    before = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
    fetch = subprocess.run(
        ["git", "fetch", "--depth", "1", "origin", BRANCH],
        cwd=repo,
        text=True,
        capture_output=True,
    )
    if fetch.returncode != 0:
        after = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
        print(f"update skipped, fetch failed ({before} -> {after}): {fetch.stderr.strip()}")
        return
    merge = subprocess.run(
        ["git", "merge", "--ff-only", "FETCH_HEAD"], cwd=repo, text=True, capture_output=True
    )
    after = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
    if merge.returncode != 0:
        print(f"update skipped, fast-forward merge failed ({before} -> {after}): {merge.stderr.strip()}")
        return
    print(f"updated {repo} {before} -> {after}")


def write_wrapper() -> None:
    TARGET.mkdir(parents=True, exist_ok=True)
    path = TARGET / "SKILL.md"
    if path.exists():
        old = path.read_text()
        if old == WRAPPER:
            return
        if MARKER not in old:
            shutil.copy(path, path.with_suffix(".md.bak"))
            print(f"backed up hand-edited {path.name} to {path.with_suffix('.md.bak').name}")
    path.write_text(WRAPPER)
    print(f"wrote {path}")


def link_skills(repo: Path) -> None:
    src = repo / "pstack" / "skills"
    if not src.is_dir():
        sys.exit(f"no pstack skills at {src}, is the checkout broken?")
    link = TARGET / "skills"
    if link.is_symlink():
        if link.resolve() == src.resolve():
            return
        link.unlink()
    elif link.exists():
        sys.exit(f"{link} is a real directory, refusing to replace it")
    link.symlink_to(src, target_is_directory=True)
    print(f"linked {link} -> {src}")


def check(repo: Path) -> None:
    wrapper = (TARGET / "SKILL.md").read_text()
    header, _, body = wrapper.partition("\n---\n")
    fields = dict(line.split(": ", 1) for line in header.removeprefix("---\n").splitlines())
    assert fields.get("name") == "pstack", "frontmatter missing or misordered"
    assert fields.get("disable-model-invocation") == "true", "pstack must be opt-in"
    # A bare ": " inside a value makes YAML read a nested mapping and pi drops the skill.
    assert all(": " not in v for v in fields.values()), f"colon in frontmatter value: {fields}"
    assert body.strip(), "wrapper body is empty"
    assert (TARGET / "skills").resolve() == (repo / "pstack" / "skills").resolve(), "bad link"
    required = (
        TARGET / "skills" / "poteto-mode" / "SKILL.md",
        TARGET / "skills" / "poteto-mode" / "playbooks" / "feature.md",
    )
    for path in required:
        assert path.is_file(), f"missing required pstack file: {path}"
    count = len(list((TARGET / "skills").glob("*/SKILL.md")))
    print(f"ok: 1 hidden skill registered, 0 system-prompt entries; {count} pstack files readable under {TARGET}/skills")


def main() -> None:
    repo = Path(sys.argv[1]).expanduser() if len(sys.argv) > 1 else DEFAULT_REPO
    sync_repo(repo)
    write_wrapper()
    link_skills(repo)
    check(repo)


if __name__ == "__main__":
    main()
